# Generated by Django 4.0.5 on 2022-06-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='money_amount',
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='money_amount',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=10),
        ),
    ]
